/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'root' at '4/19/20 3:44 AM' with Gradle 2.10
 *
 * @author root, @date 4/19/20 3:44 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
